version: "3"

services:
  daab:
    build:
      context: .
      dockerfile: Dockerfile
    image: daab:final_ex
    container_name: daab
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./:/usr/src/app
      - daab:/usr/src/app/node_modules
    tty: true
    # entrypoint: bash -c "sh entrypoint.sh"

volumes:
  daab: